SamuraiApp/WebApp/Controllers/QuotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SamuraiApp.Data;
using SamuraiApp.Domain;

namespace WebApp.Controllers
{
    public class QuotesController : Controller
    {
        private readonly SamuraiContext _context;

        public QuotesController(SamuraiContext context)
        {
            _context = context;
        }

        // GET: Quotes
        public async Task<IActionResult> Index()
        {
            var samuraiContext = _context.Quotes.Include(q => q.Samurai);
            return View(await samuraiContext.ToListAsync());
        }

        // GET: Quotes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quote = await _context.Quotes
                .Include(q => q.Samurai)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (quote == null)
            {
                return NotFound();
            }

            return View(quote);
        }

        // GET: Quotes/Create
        public IActionResult Create(int samuraiId)
        {
            ViewData["SamuraiList"] = new SelectList(_context.Samurais, "Id", "Name",samuraiId);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Text,SamuraiId")] Quote quote)
        {
            if (ModelState.IsValid)
            {
                _context.Add(quote);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Samurais", new { id = quote.SamuraiId });
            }
            //ViewData["SamuraiId"] = new SelectList(_context.Samurais, "Id", "Id", quote.SamuraiId);
            return RedirectToAction("Details", "Samurais", new { id = quote.SamuraiId});
        }

        // GET: Quotes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var quote = await _context.Quotes.SingleOrDefaultAsync(m => m.Id == id);
            if (quote == null)
            {
                return NotFound();
            }
            ViewData["SamuraiId"] = new SelectList(_context.Samurais, "Id", "Name", quote.SamuraiId);
            return View(quote); 

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Text,SamuraiId")] Quote quote) {
            if (id != quote.Id) {
                return NotFound();
            }
            if (ModelState.IsValid) {
                try {
                    _context.Update(quote);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException) {
                    if (!QuoteExists(quote.Id)) {
                        return NotFound();
                    }
                    else { throw; }
                }
                return RedirectToAction("Details", "Samurais", new { id = quote.SamuraiId });
            }
            ViewData["SamuraiId"] = new SelectList(_context.Samurais, "Id", "Id", quote.SamuraiId);
            return RedirectToAction("Details", "Samurais", new { id = quote.SamuraiId });
        }

        // GET: Quotes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quote = await _context.Quotes
                .Include(q => q.Samurai)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (quote == null)
            {
                return NotFound();
            }

            return View(quote);
        }

        // POST: Quotes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var quote = await _context.Quotes.SingleOrDefaultAsync(m => m.Id == id);
            _context.Quotes.Remove(quote);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool QuoteExists(int id)
        {
            return _context.Quotes.Any(e => e.Id == id);
        }
    }
}

SamuraiApp/WebApp/Controllers/SamuraisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SamuraiApp.Data;
using SamuraiApp.Domain;

namespace WebApp.Controllers
{
    public class SamuraisController : Controller
    {
        private readonly SamuraiContext _context;

        public SamuraisController(SamuraiContext context)
        {
            _context = context;
        }

        // GET: Samurais
        public async Task<IActionResult> Index()
        {
            return View(await _context.Samurais.ToListAsync());
        }

        // GET: Samurais/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var samurai = await _context.Samurais.Include(s => s.SecretIdentity)
                .Include(s => s.Quotes)
                .SingleOrDefaultAsync(m => m.Id == id);

            if (samurai == null)
            {
                return NotFound();
            }

            return View(samurai);
        }

        // GET: Samurais/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Samurais/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Samurai samurai)
        {
            if (ModelState.IsValid)
            {
                _context.Add(samurai);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(samurai);
        }

        // GET: Samurais/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var samurai = await _context.Samurais.Include(s=>s.SecretIdentity)
                                                 .Include(s=>s.Quotes)
                                                 .SingleOrDefaultAsync(m => m.Id == id);
            if (samurai == null)
            {
                return NotFound();
            }
            return View(samurai);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //    public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Samurai samurai)
        public async Task<IActionResult> Edit(int id, Samurai samurai)
        {
            if (id != samurai.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(samurai);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SamuraiExists(samurai.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(samurai);
        }

        // GET: Samurais/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var samurai = await _context.Samurais
                .SingleOrDefaultAsync(m => m.Id == id);
            if (samurai == null)
            {
                return NotFound();
            }

            return View(samurai);
        }

        // POST: Samurais/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var samurai = await _context.Samurais.SingleOrDefaultAsync(m => m.Id == id);
            _context.Samurais.Remove(samurai);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SamuraiExists(int id)
        {
            return _context.Samurais.Any(e => e.Id == id);
        }
    }
}

SamuraiApp/WebApp/Views/Samurais/Create.cshtml
@model SamuraiApp.Domain.Samurai

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Samurai</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SamuraiApp/WebApp/Views/Samurais/Delete.cshtml
@model SamuraiApp.Domain.Samurai

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Samurai</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SamuraiApp/WebApp/Views/Samurais/Details.cshtml
@model SamuraiApp.Domain.Samurai

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Samurai</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SecretIdentity.RealName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SecretIdentity.RealName)
        </dd>
    </dl>
</div>
<table class="table">
    <thead>
        <tr>
            <th>Quotes</th>
            <th></th>
        </tr>
    </thead>
    @foreach (var item in Model.Quotes)
    {
        <tr>
             <td>@item.Text </td>
         </tr>
    }
</table>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SamuraiApp/WebApp/Views/Samurais/Edit.cshtml
@model SamuraiApp.Domain.Samurai

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Samurai</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="SecretIdentity.Id" />
            <input type="hidden" asp-for="SecretIdentity.SamuraiId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecretIdentity.RealName" class="control-label"></label>
                <input asp-for="SecretIdentity.RealName" class="form-control" />
                <span asp-validation-for="SecretIdentity.RealName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<hr style= " border-style:solid; border-width: 1.5px;"/>

<table class="table">
    <thead>
        <tr>
            <th>Text</th>
            <th></th>
        </tr>
    </thead>
    @foreach (var item in Model.Quotes)
    {
        <tr>
            <td>@item.Text </td>
            <td> @Html.ActionLink("Edit", "Edit", "Quotes", new { id = item.Id, samuraiId = item.SamuraiId }, null)</td>
        </tr>
    }
</table>
<div>

    @Html.ActionLink("New Quote", "Create", "Quotes", new { samuraiId = Model.Id }, null)  |
    <a asp-action="Index">Back to Samurais List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SamuraiApp/WebApp/Views/Samurais/Index.cshtml
@model IEnumerable<SamuraiApp.Domain.Samurai>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>